# Travis CI configuration file
# http://travis-ci.org

sudo: false
language: minimal

deploy:
  provider: script
  script: bash ./.script/release.sh
  on:
    tags: true

notifications:
 email:
  on_success: never
  on_failure: always